In [45]:
'INIT'

import numpy as np
def init_cd(n: int)-> np.ndarray:
    arr = np.ones(n).astype(int)*-1
    return arr

a = 5
f = init_cd(a)

print(f)

[-1 -1 -1 -1 -1]


In [53]:
'UNION'

import numpy as np
def find(ind: int, p_cd: np.ndarray)-> int:
    #z = ind
    #while p_cd[z] >= -1:
    #        z = p_cd[z]
    #while p_cd[ind] > -1:
    #        y = p_cd[ind]
    #        p[ind] = z
    #        ind = y
    #return z
    while p_cd[ind] > -1:
        ind = p_cd[ind]
    return ind

def union(rep_1: int, rep_2: int, p_cd: np.ndarray)-> int:
    x = find (rep_1, p_cd)
    y = find (rep_2, p_cd)
        
    if x == y:
        return -1
        
    if p_cd[y] < p_cd[x]:
        p_cd[x] = y
        ret = y
    elif p_cd[y] > p_cd[x]:
        p_cd[y] = x
        ret = x
    else:
        p_cd[y] = x
        p_cd[x] -= 1
        ret =  x   
    return ret

p =np.array([-2, 0, 1, -2, 3, 4, -1, -2, 7, 8])
    
h = union(find(1, p), find(5, p), p)
print(h)
h = union(find(2, p), find(6, p), p)
print(h)
h = union(find(5, p), find(9, p), p)
print(h)

0
0
0


In [73]:
'FIND'

import numpy as np

def find(ind: int, p_cd: np.ndarray)-> int:
    z = ind
    
    # get the root (representant)
    while p_cd[z] >= 0:
        z = p_cd[z]
        
    # compress the path from u to the root
    while p_cd[ind] >= 0:
        y = p_cd[ind]
        p_cd[ind] = z
        ind = y
    return z


p =np.array([-2, 0, 1, -2, 3, 4, -1, -2, 7, 8])
h = find(9,p)
print(h)

7


In [74]:
'DICT'

from typing import ItemsView
import numpy as np
def cd_2_dict(p_cd: np.ndarray)-> dict:
    d = {}
    for i in range(len(p_cd)):
        if p_cd[i] < 0:
            d[i] = []
    for i in range(len(p_cd)):
        f = find(i, p_cd)
        d[f].append(i)    
    
    return d

p = np.array([-2, 0, 1, -2, 3, 4, -1, -2, 7, 8])
dic = cd_2_dict(p)
print(dic)


{0: [0, 1, 2], 3: [3, 4, 5], 6: [6], 7: [7, 8, 9]}


In [20]:
import numpy as np

def init_cd(n: int)-> np.ndarray:
    arr = np.ones(n).astype(int)*-1
    return arr
    
def find(ind: int, p_cd: np.ndarray)-> int:
    z = ind
    
    # get the root (representant)
    while p_cd[z] >= 0:
        z = p_cd[z]
        
    # compress the path from u to the root
    while p_cd[ind] >= 0:
        y = p_cd[ind]
        p_cd[ind] = z
        ind = y
    return z

def ccs(n: int, l: lis
  print(p)t)-> dict:
    d_cc = {} 
    p = init_cd(len(l))
    print(p)
    for u, v in l:
        r_u = find(u, p)
        r_v = find(v, p)
        if r_u != r_v:
            #add (u, v) to the proper key in cc
            if u in d_cc.keys():
                d_cc[u].append((u, v))
            elif v in d_cc.keys():
                d_cc[v].append((u, v))
            else:
                d_cc[u] = []
                d_cc[u].append((u, v))
    return d_cc

g = [(1, 2), (1, 3), (0, 4), (4, 5)]

d = ccs(4, g)
print(d)

SyntaxError: invalid syntax (<ipython-input-20-dd5afbcd5c22>, line 22)

In [33]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

f = dist_matrix(6, 20)
print(f)

[[ 0  6 15  0 18  7]
 [ 3  0  8 17  0  9]
 [15 19  0 15 10  6]
 [ 7  4  8  0  6 13]
 [ 9 14  6 19  0 17]
 [ 4  2 16  6 17  0]]


In [34]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

def greedy_tsp(dist_m: np.ndarray, node_ini=0)-> list:
    num_cities = dist_m.shape[0]
    circuit = [node_ini]
    while len(circuit) < num_cities:
        current_city = circuit[-1]
        # sort cities in ascending distance from current
        options = list( np.argsort(dist_m[ current_city ]) )
        # add first city in sorted list not visited yet
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
    return circuit + [node_ini]

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 5, 2, 8, 0]])
circuit = greedy_tsp(f)
print(circuit)


[0, 2, 4, 1, 3, 0]


In [52]:
import numpy as np

def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    longitud = 0
    for i in range(len(dist_m)):
        longitud += dist_m[circuit[i]][circuit[i+1]]
    return longitud

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 5, 2, 8, 0]])

c = greedy_tsp(f, 0)

l = len_circuit(c, f)
print(c)
print(l)
    

[0, 2, 4, 1, 3, 0]
23


In [83]:
import numpy as np

def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    longitud = 0
    for i in range(len(dist_m)):
        longitud += dist_m[circuit[i]][circuit[i+1]]
    return longitud

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 5, 2, 8, 0]])

c = [0, 1, 3, 4, 2, 0]


l = len_circuit(c, f)
print(l)

18


In [87]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    longitud = 0
    for i in range(len(dist_m)):
        longitud += dist_m[circuit[i]][circuit[i+1]]
    return longitud

def greedy_tsp(dist_m: np.ndarray, node_ini=0)-> list:
    num_cities = dist_m.shape[0]
    circuit = [node_ini]
    while len(circuit) < num_cities:
        current_city = circuit[-1]
        # sort cities in ascending distance from current
        options = list( np.argsort(dist_m[ current_city ]) )
        # add first city in sorted list not visited yet
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
    return circuit + [node_ini]

def repeated_greedy_tsp(dist_m: np.ndarray)-> list:
    circuitos = []
    longitudes = []
    for i in range(len(dist_m)):
        circuitos.append(greedy_tsp(dist_m, i))
        longitudes.append(len_circuit(circuitos[i], dist_m))

    min = np.amin(longitudes)
    index = longitudes.index(min)

    return circuitos[index]

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 6, 2, 8, 0]])
circuit = repeated_greedy_tsp(f)
print(circuit)

[1, 0, 2, 4, 3, 1]


In [7]:
from itertools import permutations
import numpy as np

def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    longitud = 0
    for i in range(len(dist_m)):
        longitud += dist_m[circuit[i]][circuit[i+1]]
    return longitud

def exhaustive_tsp(dist_m: np.ndarray)-> list:
  c = []
  l = []
  h = []

  for i in range(len(dist_m)):
    c.append(i)

  p = list(permutations(c))

  for i in p:
    l.append(list(i))

  for i in range(len(l)):
    l[i].append(l[i][0])

  min = len_circuit(l[0], dist_m)
  h = list(np.copy(l[0]))
  
  for i in l[1:]:
    aux = len_circuit(i, dist_m)
    if aux < min:
      min = aux
      h = list(np.copy(i))

  return h
      
f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 6, 2, 8, 0]])

o = exhaustive_tsp(f)
print(o)

[0, 1, 3, 4, 2, 0]
