In [45]:
'INIT'

import numpy as np
def init_cd(n: int)-> np.ndarray:
    arr = np.ones(n).astype(int)*-1
    return arr

a = 5
f = init_cd(a)

print(f)

[-1 -1 -1 -1 -1]


In [40]:
'UNION'

import numpy as np
def find(ind: int, p_cd: np.ndarray)-> int:
    #z = ind
    #while p_cd[z] >= -1:
    #        z = p_cd[z]
    #while p_cd[ind] > -1:
    #        y = p_cd[ind]
    #        p[ind] = z
    #        ind = y
    #return z
    while p_cd[ind] > -1:
        ind = p_cd[ind]
    return ind

def union(rep_1: int, rep_2: int, p_cd: np.ndarray)-> int:
    x = find (rep_1, p_cd)
    y = find (rep_2, p_cd)
        
    if x == y:
        return -1
        
    if p_cd[y] < p_cd[x]:
        p_cd[x] = y
        ret = y
    elif p_cd[y] > p_cd[x]:
        p_cd[y] = x
        ret = x
    else:
        p_cd[y] = x
        p_cd[x] -= 1
        ret =  x   
    return ret

p =np.array([-2, 0, 1, -2, 3, 4, -1, -2, 7, 8])
    
h = union(find(1, p), find(5, p), p)
print(h)
h = union(find(2, p), find(6, p), p)
print(h)
h = union(find(5, p), find(9, p), p)
print(h)

0
0
0


In [12]:
'FIND'

import numpy as np

def find(ind: int, p_cd: np.ndarray)-> int:
    z = ind
    
    # get the root (representant)
    while p_cd[z] >= 0:
        z = p_cd[z]
        
    # compress the path from u to the root
    while p_cd[ind] >= 0:
        y = p_cd[ind]
        p_cd[ind] = z
        ind = y
    return z


p =np.array([-2, 0, 1, -2, 3, 4, -1, -2, 7, 8])
h = find(9,p)
print(h)

7


In [1]:
'DICT'

from typing import ItemsView
import numpy as np
def cd_2_dict(p_cd: np.ndarray)-> dict:
    d = {}
    for i in range(len(p_cd)):
        if p_cd[i] < 0:
            d[p_cd[i]] = []
            key = p_cd[i]
        else:
            d[key] += [p_cd[i]]

    return d

p = np.array([-2, 0, 1, -2, 3, 4, -1, -2, 7, 8])
dic = cd_2_dict(p)
print(dic)


{-2: [7, 8], -1: []}


In [1]:
import numpy as np

def init_cd(n: int)-> np.ndarray:
    arr = np.ones(n).astype(int)*-1
    return arr
    
def find(ind: int, p_cd: np.ndarray)-> int:
    z = ind
    
    # get the root (representant)
    while p_cd[z] >= 0:
        z = p_cd[z]
        
    # compress the path from u to the root
    while p_cd[ind] >= 0:
        y = p_cd[ind]
        p_cd[ind] = z
        ind = y
    return z

def ccs(n: int, l: list)-> dict:
    d_cc = {} 
    p = init_cd(len(l))
    print(p)
    for u, v in l:
        r_u = find(u, p)
        r_v = find(v, p)
        if r_u != r_v:
            #add (u, v) to the proper key in cc
            if u in d_cc.keys():
                d_cc[u].append((u, v))
            elif v in d_cc.keys():
                d_cc[v].append((u, v))
            else:
                d_cc[u] = []
                d_cc[u].append((u, v))
    return d_cc

g = [(1, 2), (1, 3), (0, 4), (4, 5)]

d = ccs(4, g)
print(d)

[-1 -1 -1 -1]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [33]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

f = dist_matrix(6, 20)
print(f)

[[ 0  6 15  0 18  7]
 [ 3  0  8 17  0  9]
 [15 19  0 15 10  6]
 [ 7  4  8  0  6 13]
 [ 9 14  6 19  0 17]
 [ 4  2 16  6 17  0]]


In [3]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

def greedy_tsp(dist_m: np.ndarray, node_ini=0)-> list:
    num_cities = dist_m.shape[0]
    circuit = [node_ini]
    while len(circuit) < num_cities:
        current_city = circuit[-1]
        # sort cities in ascending distance from current
        options = list( np.argsort(dist_m[ current_city ]) )
        # add first city in sorted list not visited yet
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
    return circuit + [node_ini]

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 5, 2, 8, 0]])
circuit = greedy_tsp(f)
print(circuit)


[0, 2, 4, 1, 3, 0]


In [1]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

def greedy_tsp(dist_m: np.ndarray, node_ini=0)-> list:
    num_cities = dist_m.shape[0]
    circuit = [node_ini]
    while len(circuit) < num_cities:
        current_city = circuit[-1]
        # sort cities in ascending distance from current
        options = list( np.argsort(dist_m[ current_city ]) )
        # add first city in sorted list not visited yet
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
    return circuit + [node_ini]

def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    longitud = 0
    for i in range(len(dist_m)):
        longitud += dist_m[circuit[i]][circuit[i+1]]
    return longitud

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 5, 2, 8, 0]])

circuit = greedy_tsp(f, 1)

len = len_circuit(circuit, f)

print(len)
    

18


In [5]:
import numpy as np

def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    h = np.random.randint(w_max, size=(n_nodes, n_nodes))
    np.fill_diagonal(h, 0)
    return h 

def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    longitud = 0
    for i in range(len(dist_m)):
        longitud += dist_m[circuit[i]][circuit[i+1]]
    return longitud

def greedy_tsp(dist_m: np.ndarray, node_ini=0)-> list:
    num_cities = dist_m.shape[0]
    circuit = [node_ini]
    while len(circuit) < num_cities:
        current_city = circuit[-1]
        # sort cities in ascending distance from current
        options = list( np.argsort(dist_m[ current_city ]) )
        # add first city in sorted list not visited yet
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
    return circuit + [node_ini]

def repeated_greedy_tsp(dist_m: np.ndarray)-> list:
    aux = []
    a = []
    for i in range(len(dist_m)):
        aux.append(greedy_tsp(dist_m, i))
        a.append(len_circuit(aux[i], dist_m))
        if a[i]-a[i-1]:
            circuito = aux[i]
        
    return circuito

f = np.array([
    [0, 2, 1, 10, 25],
    [2, 0, 18, 5, 5],
    [1, 18, 0, 20, 2],
    [10, 5, 20, 0, 8],
    [25, 6, 2, 8, 0]])
circuit = repeated_greedy_tsp(f)
print(circuit)

[1, 0, 2, 4, 3, 1]


In [16]:
from itertools import permutations
import numpy as np

a = np.array([1,2,3])
p = permutations(a)

for j in list(p):
  print(j)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)
