In [7]:
import numpy as np
from typing import List, Tuple

def split(t: List) -> Tuple[List, int, List]:
    mid = t[0]
    t_l = [u for u in t if u < mid]
    t_r = [u for u in t if u > mid]
    return (t_l, mid, t_r)

h = [6,8,7,4,5,9,2]

split(h)



([4, 5, 2], 6, [8, 7, 9])

In [15]:
import numpy as np
from typing import List, Tuple, Dict, Callable, Iterable,Union
def qsel(t: np.ndarray, k: int)-> Union[int, None]:
    if len(t) == 1 and k == 0:
        return t[0]
    t_l, mid, t_r = split(t)
    m = len(t_l)
    if k == m:
        print("PRIMER IF")
        return mid
    elif k < m:
        print("SEGUNDO IF")
        return qsel(t_l, k)
    else:
        print("TERCER IF")
        return qsel(t_r, k-m-1)

h = [6,8,7,4,5,9,5]

qsel(h, 5)

7
TERCER IF
PRIMER IF


8

In [19]:
from typing import List, Tuple, Dict, Callable, Iterable,Union
def split_pivot(t: np.ndarray, mid: int)-> Tuple[np.ndarray, int, np.ndarray]:
    t_l = [u for u in t if u < mid]
    t_r = [u for u in t if u > mid]
    return (t_l, mid, t_r)

def QSel5_nr (data:List, k:int) -> Union[int, None]:
    cutoff = 5
    
    if len(data) <= cutoff:
        return sorted(data)[k-1]
    else:
        pivot_value = pivot5(data)
    
        s_1, pivot_value, s_2 = split_pivot(data, pivot_value)

        pivot_index = len(s_1)

        if (k-1) == pivot_index  :
            return pivot_value
        elif (k-1) < pivot_index :
            return QSel5_nr (s_1, k)
        else:
            return QSel5_nr (s_2, k-pivot_index-1)

h = [6,8,7,4,5,9,2]

QSel5_nr(h, 5)
        

7

In [20]:
def qsel_nr(t: np.ndarray, k: int)-> Union[int, None]:
    if(k < 0 or t is None):
        return None
    
    if(len(t)==1):
        return t[0]
    else:
        t1, p, t2 = split(t)
        m = len(t1)

        if k==m:
            ret = p
        elif k<m:
            ret = qsel_nr(t1, k)
        elif k>m:
            ret = qsel_nr(t2, k-m-1)

    return ret
        

h = [6,8,7,4,5,9,2]

qsel_nr(h, 5)


8

In [17]:
import numpy as np
from typing import List, Tuple, Dict, Callable, Iterable,Union

def split_pivot(t: np.ndarray, mid: int)-> Tuple[np.ndarray, int, np.ndarray]:
    t_l = [u for u in t if u < mid]
    t_r = [u for u in t if u > mid]
    return (t_l, mid, t_r)

h = [6,8,7,4,5,9,2]

split_pivot(h,7)


([6, 4, 5, 2], 7, [8, 9])

In [5]:
import numpy as np

def pivot5(t: np.ndarray)-> int:
    '''Calculate the medians of medians'''
    n_group = len(t) // 5
    index_median = 5 // 2 
    cutoff = 5
    sublists =  [t[j:j+ 5] for j in range(0, len(t), 5)][:n_group]
    medians = [sorted(sub)[index_median] for sub in sublists]

    if len(medians) <= cutoff:
        pivot = sorted(medians)[len(medians)//2]
    else:
        pivot = QSelect5 (medians, len(medians)//2)
        
    return pivot
    

h = [6,8,7,4,5,0,2,1,11,10,5,6,7,8,9]

pivot5(h)

6

In [21]:
from typing import List, Tuple, Dict, Callable, Iterable,Union
def QSelect5 (data:List, k:int) -> Union[int, None]:
    group_size = 5
    cutoff = 5
    
    if len(data) <= cutoff:
        return sorted(data)[k-1]
    
    pivot_value = pivot5(data)
    
    s_1, pivot_value, s_2 = split_pivot(data, pivot_value)

    pivot_index = len(s_1)

    if (k-1) == pivot_index  :
        return pivot_value
    elif (k-1) < pivot_index :
        return QSelect5 (s_1, k)
    else:
        return QSelect5 (s_2, k-pivot_index-1)
    
h = [6,8,7,4,5,9,2]

QSelect5(h, 5)

7

In [15]:
def edit_distance(str_1: str, str_2: str)-> int:
    D = np.zeros((len(x)+1, len(y)+1), dtype=int)
    D[0, 1:] = range(1, len(y)+1)
    D[1:, 0] = range(1, len(x)+1)
    
    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):
            # x[i] == y[j]
            if (x[i-1] == y[j-1]):
                D[i,j] = D[i-1, j-1]
                
            # x[i] != y[j]
            else :
                D[i, j] = min(D[i-1, j-1]+1, D[i-1, j]+1, D[i, j-1]+1)
    
    return D

# ----- Driver program ------
y = "cosa"
x = "caso"

D = D = edit_distance(x, y)
print(D)
print (f'Edit distance:{D[-1,-1]}')

Edit distance:2


In [11]:
def max_subsequence_length(str_1: str, str_2: str)-> int:
    """ Calculate  the LCS length between sequences x and y using
    matrix dynamic programming. Return matrix. """
    
    e = np.zeros((len(x)+1, len(y)+1), dtype=int)
    
    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):
            # x[i] == y[j]
            if (x[i-1] == y[j-1]):
                e[i,j] = 1 + e[i-1, j-1]
                
            # x[i] != y[j]    
            else :
                e[i, j] = max(e[i-1, j], e[i, j-1])
    return e

y = "BDCABA"
x = "ABCBDAB"

e = max_subsequence_length(x, y)
print(e)
print(f'LCS length: {e[-1,-1]}')

[[0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1]
 [0 1 1 1 1 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 3 3]
 [0 1 2 2 2 3 3]
 [0 1 2 2 3 3 4]
 [0 1 2 2 3 4 4]]
LCS length: 4


In [ ]:
def max_common_subsequence(str_1: str, str_2: str)-> str:

In [ ]:
def min_mult_matrix(l_dims: List[int])-> int: